begin;
create table if not exists public.vehicles (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  registration text not null, make text, model text, fuel_type text not null default 'diesel'
    check(fuel_type in ('petrol','diesel','electric','hybrid','lpg','other')),
  current_odometer numeric(12,2) not null default 0 check(current_odometer>=0), active boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id,registration)
);
create table if not exists public.vehicle_fuel_entries (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  vehicle_id uuid not null references public.vehicles(id) on delete cascade, purchased_at timestamptz not null default now(),
  station text, litres numeric(10,3) check(litres>=0), total_cost numeric(12,2) not null check(total_cost>=0),
  odometer numeric(12,2) check(odometer>=0), notes text, created_at timestamptz not null default now()
);
create table if not exists public.vehicle_trips (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  vehicle_id uuid not null references public.vehicles(id) on delete cascade, customer_id uuid references public.customers(id) on delete set null,
  purpose text, start_address text not null, end_address text not null, started_at timestamptz not null, ended_at timestamptz not null,
  distance_miles numeric(12,3) not null default 0 check(distance_miles>=0), start_odometer numeric(12,2), end_odometer numeric(12,2),
  tracking_mode text not null default 'manual' check(tracking_mode in ('manual','gps')), notes text, created_at timestamptz not null default now(),
  check(ended_at>=started_at)
);
create table if not exists public.vehicle_trip_points (
  id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade,
  trip_id uuid not null references public.vehicle_trips(id) on delete cascade, latitude double precision not null check(latitude between -90 and 90),
  longitude double precision not null check(longitude between -180 and 180), accuracy_meters double precision,
  recorded_at timestamptz not null, sort_order integer not null
);
create index if not exists vehicle_fuel_entries_vehicle_idx on public.vehicle_fuel_entries(vehicle_id,purchased_at desc);
create index if not exists vehicle_trips_vehicle_idx on public.vehicle_trips(vehicle_id,started_at desc);
create index if not exists vehicle_trips_customer_idx on public.vehicle_trips(customer_id);
create index if not exists vehicle_trip_points_trip_idx on public.vehicle_trip_points(trip_id,sort_order);
alter table public.vehicles enable row level security; alter table public.vehicle_fuel_entries enable row level security;
alter table public.vehicle_trips enable row level security; alter table public.vehicle_trip_points enable row level security;
do $$ declare table_name text; policy_name text; begin
  foreach table_name in array array['vehicles','vehicle_fuel_entries','vehicle_trips','vehicle_trip_points'] loop
    for policy_name in select policyname from pg_policies where schemaname='public' and tablename=table_name loop execute format('drop policy if exists %I on public.%I',policy_name,table_name); end loop;
    execute format('create policy %I on public.%I for select using(user_id=public.current_workspace_owner_id())','Workspace members can view '||table_name,table_name);
    execute format('create policy %I on public.%I for insert with check(user_id=public.current_workspace_owner_id())','Workspace members can create '||table_name,table_name);
    execute format('create policy %I on public.%I for update using(user_id=public.current_workspace_owner_id()) with check(user_id=public.current_workspace_owner_id())','Workspace members can update '||table_name,table_name);
    execute format('create policy %I on public.%I for delete using(user_id=public.current_workspace_owner_id())','Workspace members can delete '||table_name,table_name);
    execute format('drop trigger if exists workspace_activity_trigger on public.%I',table_name);
    execute format('create trigger workspace_activity_trigger after insert or update or delete on public.%I for each row execute function public.log_workspace_record_change()',table_name);
  end loop;
end $$;
drop trigger if exists workspace_activity_trigger on public.vehicle_trip_points;
notify pgrst,'reload schema'; commit;
