import { CalendarClock, Pause, Play, RefreshCw, Trash2 } from "lucide-react";
import { redirect } from "next/navigation";
import { createRecurringJob, deleteRecurringJob, generateRecurringJobsNow, updateRecurringStatus } from "@/app/dashboard/recurring/actions";
import { AppShell } from "@/components/app-shell";
import { currency, formatDate } from "@/lib/documents";
import { hasProAccess } from "@/lib/subscription";
import { createClient } from "@/lib/supabase/server";

const factors: Record<string, number> = { weekly: 52/12, fortnightly: 26/12, monthly: 1, quarterly: 1/3, annually: 1/12 };
export default async function RecurringPage({ searchParams }: { searchParams: Promise<{ message?: string }> }) {
  const search = await searchParams; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login");
  const [{ data: profile }, customersResult, plansResult] = await Promise.all([supabase.from("profiles").select("plan,subscription_status,trial_expires_at").eq("id",user.id).maybeSingle(), supabase.from("customers").select("id,name").eq("user_id",user.id).order("name"), supabase.from("recurring_jobs").select("id,title,frequency,status,next_run_date,expected_value,visit_time,customers(name)").eq("user_id",user.id).order("next_run_date")]);
  if (!hasProAccess(profile)) redirect("/pricing?message=Recurring Work is available on Tradio Pro and Elite."); const error=customersResult.error??plansResult.error; if(error) redirect(`/dashboard?message=${encodeURIComponent(error.message)}`);
  const plans=plansResult.data??[]; const monthly=plans.filter((p)=>p.status==="active").reduce((sum,p)=>sum+Number(p.expected_value)*Number(factors[p.frequency]??0),0);
  return <AppShell active="recurring" plan={profile?.plan}><header className="app-page-header"><div><p className="eyebrow">Pro service plans</p><h1 className="page-title">Recurring jobs and customer visits.</h1></div><form action={generateRecurringJobsNow}><button className="btn-secondary"><RefreshCw size={16}/>Generate upcoming</button></form></header><div className="app-page-body space-y-6">{search.message?<p className="notice">{search.message}</p>:null}<section className="grid gap-4 sm:grid-cols-2"><div className="surface-pad"><p className="text-sm text-slate-500">Active service plans</p><p className="mt-2 text-2xl font-semibold">{plans.filter((p)=>p.status==="active").length}</p></div><div className="surface-pad"><p className="text-sm text-slate-500">Expected recurring monthly revenue</p><p className="mt-2 text-2xl font-semibold">{currency(monthly)}</p></div></section>
  <section className="surface-pad"><div className="mb-5 flex items-center gap-3"><CalendarClock className="text-copper"/><div><h2 className="font-semibold">Create recurring work</h2><p className="text-sm text-slate-500">Upcoming jobs and calendar visits are generated automatically.</p></div></div><form action={createRecurringJob} className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><select className="field-control" name="customer_id" required><option value="">Choose customer</option>{(customersResult.data??[]).map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input className="field-control" name="title" placeholder="Job title" required/><input className="field-control" name="job_type" placeholder="Job type"/><select className="field-control" name="frequency"><option value="weekly">Weekly</option><option value="fortnightly">Fortnightly</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="annually">Annually</option></select><input className="field-control" name="start_date" required type="date"/><input className="field-control" name="end_date" type="date"/><input className="field-control" defaultValue="09:00" name="visit_time" type="time"/><input className="field-control" defaultValue="60" min="15" name="duration_minutes" step="15" type="number"/><input className="field-control" min="0" name="expected_value" placeholder="Expected job value" step="0.01" type="number"/><input className="field-control" name="location" placeholder="Location"/><textarea className="field-control min-h-20 md:col-span-2" name="description" placeholder="Job description"/><textarea className="field-control min-h-20 md:col-span-2" name="notes" placeholder="Notes and materials"/><label className="flex items-center gap-2 text-sm font-medium"><input defaultChecked name="send_reminder" type="checkbox"/> Email appointment reminder</label><button className="btn-accent xl:col-span-3">Create service plan</button></form></section>
  <section className="surface overflow-hidden"><div className="border-b border-field px-5 py-4"><h2 className="font-semibold">Service plans</h2></div><div className="divide-y divide-field">{plans.length?plans.map((plan)=>{const customer=Array.isArray(plan.customers)?plan.customers[0]:plan.customers;return <article className="grid gap-4 px-5 py-5 lg:grid-cols-[1fr_auto] lg:items-center" key={plan.id}><div><div className="flex flex-wrap gap-2"><h3 className="font-semibold">{plan.title}</h3><span className="status-pill bg-field text-forest">{plan.status}</span></div><p className="mt-1 text-sm text-slate-600">{customer?.name} · {plan.frequency} · next {formatDate(plan.next_run_date)}</p><p className="mt-1 text-sm font-semibold">{currency(plan.expected_value)} per visit</p></div><div className="flex flex-wrap gap-2"><form action={updateRecurringStatus}><input name="id" type="hidden" value={plan.id}/><input name="status" type="hidden" value={plan.status==="active"?"paused":"active"}/><button className="btn-secondary">{plan.status==="active"?<Pause size={15}/>:<Play size={15}/>} {plan.status==="active"?"Pause":"Resume"}</button></form><form action={deleteRecurringJob}><input name="id" type="hidden" value={plan.id}/><button className="btn-secondary"><Trash2 size={15}/>Delete</button></form></div></article>;}):<p className="px-5 py-8 text-sm text-slate-500">No recurring work yet.</p>}</div></section></div></AppShell>;
}
