"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { sendSmtpEmail } from "@/lib/smtp";
import { createClient } from "@/lib/supabase/server";
function value(f:FormData,k:string){const v=f.get(k);return typeof v==="string"?v.trim():"";}
function go(jobId:string,message:string):never{redirect(`/dashboard/jobs/${jobId}/completion?message=${encodeURIComponent(message)}`);}
async function requireJob(jobId:string){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const{data:job}=await supabase.from("jobs").select("id,title,customer_id,customers(name,email)").eq("id",jobId).eq("user_id",user.id).maybeSingle();if(!job)redirect("/dashboard/jobs?message=Job+not+found");return{supabase,user,job};}
export async function saveCompletionReport(formData:FormData){const jobId=value(formData,"job_id");const{supabase,user}=await requireJob(jobId);const{data:existing}=await supabase.from("job_completion_reports").select("status").eq("job_id",jobId).maybeSingle();if(existing?.status==="signed")go(jobId,"Signed reports cannot be changed.");const{error}=await supabase.from("job_completion_reports").upsert({completed_by_name:value(formData,"completed_by_name")||null,job_id:jobId,materials_used:value(formData,"materials_used")||null,recommendations:value(formData,"recommendations")||null,summary:value(formData,"summary")||null,user_id:user.id,work_performed:value(formData,"work_performed")||null,updated_at:new Date().toISOString()},{onConflict:"job_id"});if(error)go(jobId,error.message);revalidatePath(`/dashboard/jobs/${jobId}/completion`);go(jobId,"Completion report saved.");}
export async function emailCompletionReport(formData:FormData){const jobId=value(formData,"job_id");const{supabase,job}=await requireJob(jobId);const{data:report}=await supabase.from("job_completion_reports").select("token,status").eq("job_id",jobId).maybeSingle();if(!report)go(jobId,"Save the report before sending it.");if(report.status==="signed")go(jobId,"This report is already signed.");const customer=Array.isArray(job.customers)?job.customers[0]:job.customers;if(!customer?.email)go(jobId,"The customer does not have an email address.");const from=process.env.EMAIL_FROM||process.env.SMTP_USER;if(!from)go(jobId,"Email is not configured.");const site=(process.env.NEXT_PUBLIC_SITE_URL||process.env.APP_URL||"https://tradio.uk").replace(/\/$/,"");const link=`${site}/completion/${report.token}`;try{await sendSmtpEmail({from,html:`<p>Hi ${customer.name??""},</p><p>Please review and sign the completion report for ${job.title}.</p><p><a href="${link}">Review and sign report</a></p>`,subject:`Completion report: ${job.title}`,text:`Please review and sign the completion report: ${link}`,to:customer.email});}catch(error){go(jobId,error instanceof Error?error.message:"Email could not be sent.");}await supabase.from("job_completion_reports").update({sent_at:new Date().toISOString(),status:"sent"}).eq("job_id",jobId);revalidatePath(`/dashboard/jobs/${jobId}/completion`);go(jobId,"Completion report sent to the customer.");}
